/*
 * Which events does each crest listen to, in the LEGACY tree?
 *
 * This is the one parity check on crest CONTENT that can run before the combat
 * engine and the pipeline are wired together: a crest that has quietly lost an
 * event in translation shows up here immediately, and a crest listening to one
 * event too many does too.
 *
 * It is exactly the check the legacy `meldeWappen` performs at startup, turned
 * into a fixture.
 */
import { writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const P = await import(join(ROOT, 'quelle/kern.js'));

const faelle = P.WAPPEN_LISTE.map(id => {
  const w = P.WAPPEN[id];
  return {
    id,
    name: w.name,
    zeichen: w.zeichen,
    tinktur: w.tinktur,
    seltenheit: w.seltenheit,
    text: w.text,
    hinweis: w.hinweis,
    hoert: Object.keys(w.hoert).sort(),
  };
});

const raus = {
  _hinweis: 'Generated by scripts/goldenCrestShapes.mjs. What each legacy crest '
    + 'listens to, plus its card text. Do not hand-edit.',
  faelle,
};
writeFileSync(join(ROOT, 'src/tests/fixtures/crestShapes.golden.json'),
  JSON.stringify(raus, null, 1) + '\n');

const aufAllem = faelle.filter(f => f.hoert.length === P.EREIGNIS_LISTE.length).length;
console.log(faelle.length + ' Wappen. ' + aufAllem + ' hoeren auf ALLE '
  + P.EREIGNIS_LISTE.length + ' Ereignisse, die uebrigen auf '
  + faelle.filter(f => f.hoert.length !== P.EREIGNIS_LISTE.length)
      .reduce((s, f) => s + f.hoert.length, 0) + ' zusammen.');
